### ISSUE TITLE
delicious isn't working

### ISSUE THREAD

**Issue by deuxio** [ollieglass/share-counter#9]
```
NoMethodError: undefined method `[]' for nil:NilClass
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/share-counter-0.0.7/lib/share-counter.rb:43:in `delicious'
	from (irb):9
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/console.rb:90:in `start'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands.rb:17:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `block in require'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
	from /Users/bricemaurin/code/deuxio/sharecounter/bin/rails:8:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:241:in `load'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:241:in `block in load'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:241:in `load'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/commands/rails.rb:6:in `call'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/command_wrapper.rb:38:in `call'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:183:in `block in serve'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:156:in `fork'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:156:in `serve'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by seethemhigh** [comment]
Has anybody been getting a non -1 response? Seems like Delicious has shutdown this particular API url.

**Comment by ollieglass** [comment]
Is there any other Delicious API call we could use to get the share count? Or can it be scraped from a page?

**Comment by seethemhigh** [comment]
Yeah, scraping seems to be an option. I'll look further into it.

**Comment by ollieglass** [comment]
Solved by your using the new API - thanks!
